### ISSUE TITLE
[MATERIAL] Fazer lsita de materiais necessários para a automação na Anglo

### ISSUE THREAD

**Issue by Name-LK** [Engertech/Docs#18]
# Contextualização
Com base no relatório de visita feito no dia 25-09-2024, criar uma lista de materiais que satisfaça as demandas em questão

# Tasks
- [ ] Criar circuito da caixa de sobrepor com o sistema de bypass
- [x] Verificar a quantidade de IoTs que já temos
-  47 Qairs - 7 Qpower
- [ ] Personalizar o circuito para cada quadro elétrico
